version: "3.9"

services:

  example-api:
    container_name: example-api
    hostname: example-api
    image: example-api:0.0.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/share/nginx/html/
    command: [ nginx-debug, '-g', 'daemon off;' ]
